title: 학스의 개발일지
description: 개발자
site_title: '학스의 개발일지'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: hacs2772
blog_url: https://www.nagekar.com
email: abhishek@nagekar.com
keybase_username: hacs2772
twitter_username: hacs2772
reddit_username: hacs2772

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 