title: 학스의 개발일지
description: 개발자
site_title: '학스의 개발일지'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: hacs2772
blog_url: https://blog.naver.com/hacs2772
email: gkwlgns120@naver.com
keybase_username: hacs2772
twitter_username: haji_memashitte
reddit_username: hacs2772

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 